Devanshi Login Error
Sabhya-Mentor-Programme/payment-solution pull request #8
Opened 2022-02-20 11:30 UTC by Deva1106

![login error](https://user-images.githubusercontent.com/97894034/154840279-481e6a4d-f196-4a99-99fd-4abd0614a458.JPG)

in this one my register page active it is also refreshing when i entered data but not showing it in database and login page is showing a blank page even when i crosschecked it with register page as well as mern repository code. Plz guide me.

2022-02-21 08:03 UTC, sbhaya commented on client/src/components/auth/Login.js
> +  }, [error, isAuthenticated, props.history]);
@Devanshi, kindly remove `props.history` as in the updated version of react-router we used "useNavigate" instead of "useHistory".
Just delete `props.history`, and then save and run the code, see if it works. Otherwise inspect the page, and share the screenshot of the error.

2022-02-21 08:09 UTC, sbhaya commented on client/src/components/auth/Login.js
> +              value={name}
@Deva1106 Kindly check the figma file and see what all attributes are required for the login page. Name field is only for register page and not Login.

2022-02-21 08:18 UTC, sbhaya requested changes

2022-02-21 08:18 UTC, sbhaya commented on client/src/components/auth/Register.js
> +const ActionButton = styled(SubmitButton)`
Kindly uncomment the line 28-35, otherwise, styling for this Button will not be applicable.

2022-02-21 08:18 UTC, sbhaya commented on client/src/components/auth/Register.js
> +              value={OTP}
The variable has to be defined before using it. If you will observe lines 88-91, 'OTP' is not defined there, you cannot pass a value to a variable(initialize a variable) that is not defined previously.

2022-02-21 11:34 UTC, Deva1106 commented on client/src/components/auth/Register.js
> +              value={OTP}
di uske liye react otp input npm package install karna hoga kya
https://www.npmjs.com/package/react-otp-input

2022-02-21 11:44 UTC, sbhaya commented on client/src/components/auth/Register.js
> +              value={OTP}
No, the link that you have shared is for OTP UI. I am talking about the variable that will hold the value of the inputted OTP. The way variables are defined in lines 88-91, add OTP variable there.

2022-02-22 12:22 UTC, sbhaya approved these changes

2022-02-22 12:23 UTC, merged